version: '3'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: strongpass
      POSTGRES_USER: kb
      POSTGRES_DB: logger
    ports:
      - "5432:5432"
    
    volumes:
      - ./data:/var/lib/postgresql/data
